#!/bin/bash

# Docker and Kubernetes
function install_docker_k8s {
    # Add Docker repository
    DOCKER_REMOTE="https://download.docker.com/linux/ubuntu"
    DOCKER_REPO="deb [arch=amd64] ${DOCKER_REMOTE} bionic stable"
    add_apt_repo "Docker CE" "${DOCKER_REMOTE}/gpg" "$DOCKER_REPO" docker-ce

    # Add kubernetes repository
    K8S_GPG="https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    K8s_REPO="deb http://apt.kubernetes.io/ kubernetes-xenial main"
    add_apt_repo "Kubernetes" "$K8S_GPG" "$K8s_REPO" kubernetes

    # Add Google Cloud repository
    GCLOUD_REMOTE="http://packages.cloud.google.com/apt"
    GCLOUD_GPG="${GCLOUD_REMOTE}/doc/apt-key.gpg"
    GCLOUD_REPO="deb $GCLOUD_REMOTE cloud-sdk-bionic main"
    add_apt_repo "GCloud" "$GCLOUD_GPG" "$GCLOUD_REPO" gcloud

    # Install Docker and Kubernetes
    superuser_do apt install -y docker-ce kubeadm kubelet kubectl kubernetes-cni google-cloud-sdk

    whiptail --title "Finished" --msgbox "GCloud installed; run 'gcloud init' if this is a new installation." 8 56
}