#!/bin/bash

# Dropbox
function install_dropbox {
	# Variables
	NAME="Dropbox"
	PACKAGE="dropbox_2018.11.28"   # Only appears to have latest version in repo; check link below if this 404's
	REMOTE="https://linux.dropbox.com/packages/ubuntu"
	# Download and install remote package
	install_remote_package $NAME $PACKAGE $REMOTE install_thirdparty
}