#!/bin/bash

# Private Internet Access
function install_pia {
    # Variables
    # Checksums and versions from here: https://www.privateinternetaccess.com/pages/changelog
    NAME="Private Internet Access"
    RUN_FILE=pia-linux-1.1.1-02545.run
    CHECKSUM=54658fa3d9b1e85a97a854b9fe120bc27644734df509cd49f555a603dd7cb399
    # Start
    echo_message header 'Begin '$NAME' installation'
    # Download
    echo_message info 'Downloading run file for Private Internet Access...'
    curl -O https://installers.privateinternetaccess.com/download/${RUN_FILE}
    # Verify download via sha256sum
    echo_message info 'Verifying download using SHA-256...'
    sha256sum ${RUN_FILE} | grep $CHECKSUM &> /dev/null
    EXITSTATUS=$?
    if [ $EXITSTATUS = 1 ]; then
        # If checksum fails
        echo_message error 'Error: checksums do not match. Aborting...'
        whiptail --title "Error" --msgbox "Verification of $NAME download failed." 8 56
        rm $RUN_FILE
        thirdparty
    else
        # If checksum succeeds
        echo_message success "Checksums look good. Proceeding"
        # Run install script
        echo_message info 'Running install script...'
        sh $RUN_FILE
        # Cleanup and finish
        rm $RUN_FILE
        echo_message success "Installation of '$RUN_FILE' complete."
        whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 56
        thirdparty
    fi
}